# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Acvqh5rGgXG0PzY4kh8gQMfeH6MTn8iN
"""

L1 = [2, 4, 6, 10]
L2=L1
del(L2[2])
print(L5)

L1 = [2, 4, 6, 10]
L2=L1
del(L2[2])
print(L1)

import numpy as np 
import tensorflow as tf

import numpy as np 
import tensorflow as tf

D= {'AP':490, 'HB':333, 'AS':312}
del D['AP']

D= {'AP':490, 'HB':333, 'AS':312}
D['TL']= "450"
D
D['HLR']= "420"
D

print(min(1, 2, 3))
print(max(1, 2, 3))

print(abs(32))
print(abs(-32))

print("You've successfully run some Python code")
print("Congratulations!")